#!/usr/bin/env python3
"""Train and persist IsolationForest and XGBoost models for IGU Sentinel.

Usage:
    python train_models.py

What it does:
  1. Loads all 7 fixture JSONL files (benign + 6 threat classes) from tests/fixtures/.
  2. Augments with synthetic flows from traffic_gen/ configs (≥100 flows per class).
  3. Trains IsolationForest on all confirmed-benign flows.
  4. Trains XGBClassifier on all labeled flows (benign + 6 classes).
  5. Saves models to models/ (versioned, never overwrites previous versions).
  6. Prints a brief training report so you can verify sanity before demo.

Run this once before starting the service or running tests.  The API loads
the persisted models at import time (lazy warm-start).
"""

import json
import sys
import logging
from pathlib import Path

# ── project root on path ─────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from igu_sentinel.schemas import FlowRecord
from igu_sentinel.detect.isoforest import train_isoforest
from igu_sentinel.detect.xgb import train_xgb, THREAT_CLASSES

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
log = logging.getLogger(__name__)

FIXTURES_DIR = ROOT / "tests" / "fixtures"
ALL_CLASSES = ["benign"] + [c for c in THREAT_CLASSES if c != "benign"]


# ── helpers ───────────────────────────────────────────────────────────────────

def load_fixture_flows(threat_class: str) -> list[FlowRecord]:
    """Load FlowRecords from tests/fixtures/<threat_class>_sample.jsonl."""
    fpath = FIXTURES_DIR / f"{threat_class}_sample.jsonl"
    flows: list[FlowRecord] = []
    if not fpath.exists():
        log.warning("Fixture file not found: %s", fpath)
        return flows
    with open(fpath) as fh:
        for line in fh:
            line = line.strip()
            if line:
                flows.append(FlowRecord(**json.loads(line)))
    return flows



def _sample_across_variants(flows: list, target_count: int) -> list:
    """Sample evenly across the whole generated list instead of taking the head.

    run_traffic_gen() emits each YAML variant's flows in order, and the first
    variant alone can produce thousands of flows. Slicing flows[:target_count]
    therefore drew the ENTIRE training set from variant #1 - so the model only
    ever saw one rate/size/port combination per threat class, which is exactly
    the tool-fingerprint overfitting CLAUDE.md warns against. Striding samples
    every variant.
    """
    if not flows or target_count <= 0:
        return []
    if len(flows) <= target_count:
        return flows
    step = len(flows) / float(target_count)
    return [flows[int(i * step)] for i in range(target_count)]


def generate_synthetic_flows(
    threat_class: str, target_count: int = 150
) -> list[FlowRecord]:
    """Generate synthetic flows via traffic_gen/ harness.

    Loads the YAML config for the given threat class (or benign) if it exists,
    calls runner.run_traffic_gen(), and returns up to target_count FlowRecords.

    Returns [] if the config file is missing (caller falls back to fixtures only).
    """
    # traffic_gen configs only exist for the 6 threat classes, not benign.
    config_map = {
        "volumetric_ddos": "ddos.yaml",
        "c2_beaconing": "beaconing.yaml",
        "dga_dns_tunneling": "dns_tunneling.yaml",
        "encrypted_malware": "encrypted_malware.yaml",
        "recon_scanning": "scanning.yaml",
        "data_exfiltration": "exfiltration.yaml",
    }
    if threat_class not in config_map:
        return []

    config_path = ROOT / "igu_sentinel" / "traffic_gen" / "config" / config_map[threat_class]
    if not config_path.exists():
        log.warning("traffic_gen config missing: %s", config_path)
        return []

    try:
        from igu_sentinel.traffic_gen.runner import run_traffic_gen
        labeled = run_traffic_gen(str(config_path))
        # runner returns [{threat_class: str, flow: FlowRecord}, ...]
        flows = [item["flow"] for item in labeled if item["threat_class"] == threat_class]
        return _sample_across_variants(flows, target_count)
    except Exception as exc:
        log.warning("traffic_gen failed for %s: %s", threat_class, exc)
        return []


def _jitter_benign(flows: list[FlowRecord], multiplier: int = 10) -> list[FlowRecord]:
    """Expand benign fixture by adding light Gaussian jitter.

    Benign flows are fewer in fixture files than attack flows generated by
    traffic_gen.  This multiplies benign data so the classifier is not
    numerically dominated by attack classes.

    Jitter magnitude is ±5% of each feature value — small enough not to cross
    class boundaries but large enough to improve generalisation.
    """
    import random, copy
    random.seed(0)
    jittered: list[FlowRecord] = list(flows)  # start with originals

    for _ in range(multiplier - 1):
        for f in flows:
            scale = 1.0 + random.gauss(0, 0.05)
            new_f = f.model_copy(deep=True)
            new_f = FlowRecord(
                flow_id=f"{f.flow_id}_j{_}",
                timestamp=f.timestamp,
                src_port=f.src_port,
                dst_port=f.dst_port,
                protocol=f.protocol,
                packet_size_stats={
                    k: max(0.0, v * scale)
                    for k, v in f.packet_size_stats.items()
                },
                inter_arrival_stats={
                    k: max(1e-6, v * scale)
                    for k, v in f.inter_arrival_stats.items()
                },
                entropy=min(8.0, max(0.0, f.entropy * scale)),
                byte_ratio=min(1.0, max(0.0, f.byte_ratio * scale)),
                ttl=f.ttl,
                ja4=f.ja4,
                beacon_interval_stats=f.beacon_interval_stats,
                dns_ngram_entropy=f.dns_ngram_entropy,
                fanout_count=f.fanout_count,
            )
            jittered.append(new_f)
    return jittered


# ── main ──────────────────────────────────────────────────────────────────────

def main() -> int:
    """Train both models and return exit code."""
    print("=" * 60)
    print("IGU Sentinel — Model Training")
    print("=" * 60)

    all_flows: list[FlowRecord] = []
    all_labels: list[str] = []
    benign_flows: list[FlowRecord] = []

    class_stats: dict[str, int] = {}

    for cls in ALL_CLASSES:
        # Load fixtures.
        fixture_flows = load_fixture_flows(cls)
        print(f"  {cls:25s}: {len(fixture_flows):4d} fixture flows", end="")

        # Augment with synthetic data for attack classes.
        synthetic_flows: list[FlowRecord] = []
        if cls != "benign":
            synthetic_flows = generate_synthetic_flows(cls, target_count=150)
            print(f" + {len(synthetic_flows):4d} synthetic", end="")

        class_flows = fixture_flows + synthetic_flows

        # Expand benign with jitter to keep class balance reasonable.
        if cls == "benign":
            class_flows = _jitter_benign(fixture_flows, multiplier=15)
            benign_flows = class_flows  # used separately for IsoForest
            print(f" → {len(class_flows):4d} after jitter", end="")
        else:
            # All benign flows also feed isoforest training.
            benign_flows.extend([])  # benign is set above from jitter

        print()
        class_stats[cls] = len(class_flows)
        all_flows.extend(class_flows)
        all_labels.extend([cls] * len(class_flows))

    print()
    print(f"Total training set: {len(all_flows)} flows across {len(set(all_labels))} classes")
    for cls, cnt in class_stats.items():
        pct = cnt / len(all_flows) * 100
        print(f"  {cls:25s}: {cnt:5d} ({pct:5.1f}%)")

    # ── IsolationForest (benign-only) ─────────────────────────────────────────
    print()
    print("Training IsolationForest on benign flows...")
    try:
        train_isoforest(benign_flows)
        print(f"  ✓ IsolationForest trained on {len(benign_flows)} benign flows")
    except Exception as exc:
        print(f"  ✗ IsolationForest training failed: {exc}")
        return 1

    # ── XGBoost (all classes) ─────────────────────────────────────────────────
    print()
    print("Training XGBoost on all labeled flows...")
    try:
        train_xgb(all_flows, all_labels)
        print(f"  ✓ XGBoost trained on {len(all_flows)} flows, {len(set(all_labels))} classes")
    except Exception as exc:
        print(f"  ✗ XGBoost training failed: {exc}")
        return 1

    # ── Sanity check: score a few flows ─────────────────────────────────────
    print()
    print("Sanity check — scoring fixture samples:")
    from igu_sentinel.detect.isoforest import score_isoforest
    from igu_sentinel.detect.xgb import predict_xgb

    for cls in ["benign", "volumetric_ddos", "c2_beaconing", "recon_scanning"]:
        fixture_flows_cls = load_fixture_flows(cls)
        if not fixture_flows_cls:
            continue
        flow = fixture_flows_cls[0]
        iso = score_isoforest(flow)
        xgb_s = predict_xgb(flow)
        print(
            f"  {cls:25s}: iso_raw={iso.raw_score:.3f}  iso_cal={iso.calibrated_probability:.3f}"
            f"  xgb_threat={xgb_s.raw_score:.3f}  xgb_guess={xgb_s.threat_class_guess}"
        )

    print()
    print("Training complete.  Models saved to models/")
    print("Run: python eval.py   ← to see accuracy / F1 / confusion matrix")
    return 0


if __name__ == "__main__":
    sys.exit(main())
